name: Android Build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Execute Gradle command - assembleDebug
        run: ./gradlew assembleDebug
          
      - name: Upload artifact to Firebase App Distribution
        run: |
          npm install -g firebase-tools
          firebase --version
          firebase appdistribution:distribute --app ${{ secrets.APP_ID }} --token ${{ secrets.FIREBASE_TOKEN }} --groups testers --file app/build/outputs/apk/debug/app-debug.apk

