name: Android Build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run unit tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: app:testDebugUnitTest feature:home:testDebugUnitTest --stacktrace

      - name: Assemble app
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleDebug --stacktrace

      - name: Run Detekt
        uses: gradle/gradle-build-action@v2
        with:
          arguments: detekt

      - name: Upload Artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.3.2
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: app/build/outputs/apk/debug/app-debug.apk
          releaseNotes: "Hey! This my first integrate Firebase distributions with Github Actions"
